### ISSUE TITLE
机器人回答出错

### ISSUE THREAD

**Issue by rhZhang0228** [rxf113/mirai-qq-bot#1]
当我给机器人发消息时，出错了，并且乱码，我使用的是jdk8版本，并且能正常输出中文字符，似乎不是我的原因。具体报错如下：
2022-12-12T13:15:05.438+08:00  INFO 1484 --- [atcher-worker-1] com.rxf113.miraiqqbot.chat.MiraiConfig   : who at me , nickName:[‭]
2022-12-12T13:15:06.715+08:00  INFO 1484 --- [atcher-worker-1] com.rxf113.miraiqqbot.chat.HttpUtil      : session response:       �zgo�X����������$�=�0S�D1�o�3����ig��?X>u*��㣪��_�B]o*���"�����M���CP>���8��l6�͇>���wa����)�"(�w��}�}��)����}_?͐��TU�A�?]�:x�xW�}0�����6^�]�?�W�	{�O|�'�x���v��Ϳfud�?
��,�"x~h+�껯P�*)�`����*ϫ�'4cLu��_QM����~0&^����5)�>q��s����'O�l�A������ɋ�]�/y����󠌂��u�6ȟ>��A����/v=����e��N���~J��B�d�/��|�Z����a�Vy���P?��i�%?c�U<ݝ��z���
�7)���w%�2z
�1��aӵ������]�U�о�TeжU����I������WH�A�˕�k��*Nr��}��w�x�ӿ��t�w^U�i�.����0��I��/���e���w��8𲤌6I���`�%}p�2���*7I��oh��EB_�,��k����w���V���}��ߟ]������3���_����?0�t�w��������v~2����ؿ�视s�j1����FpFG{���)��WUYt��zMǤ��/�~b�w����a�m��vwK^��a��~�չ��/�2��u�,j�������C��y�����n׷��
�t��ߕU�
*���.J�?ZgyFQ��� ������I �o����|�^�OEm���~���rgS����6��~���I�l�p�TC�u
�AX���n+������ܰj�ﴽ�6�+�燝S';g��]t]R���x��/�K�=�ցa0��}b�~����R�B�*k/官��#�MO����9��q�������TE�>l���:x~p�:O<��n~���U���̓ҫ����,��|$��ʇO�6
�a3:�<?��˹�X�psD�����>�'��D�Dڲ�*~T����ʄ��S�S&DL{�x�[p&�X�j�U��D��d��`���bi'o/���v�<��ӫ]/1�őך��V����`Ю��`�0�b/��E0 �̖XNOGf^����A�
��4Ok�C{5׷�Ę>tRsXqc�g�9�����ZYgd/��m[��d��So		����q\��QgrP4K�l�R��Dc��?н��)�	���&��*�
QO�(�3ad=�W	Ⳗ��鲏#C�V�)9=�\� ��^:-yZ+�dڪU�%��W&bE�Sun�	m~���m���~�,?�Nq
ϝ�t�g/�PjLQS� ��H
ڇ�e�^b���|ņ�I��+�C�K=��Ȃ�>)��v��!Y�T/�h��n�aƚyRy�i����d�~��^tN�}E�QVo���t��'
t��k7>n��h0@�Vi�ԫ�#�R\��9	�y�cx�`රyy�%%���"�
>�d��XD���`o���{v.lf�]iSN32Y�Ŗ<�芟��Z)�5ɔ�n^&�g/h�+�#p؛�ᅴ}cE0���#ip)|N1gl����6���J��uX�!U�1T�5r�<f��hS3�U�ס:�qAp3Cy�5 ��-p6��i�D;p�]������N��77�ݓu��{�s��R N�ŲO�
�7�t����v
 �lm�A�SmCycZ�B\��YY	2�k�,#��^K�p�����h5�ѝ��iᡛ1J$;��[q�� ��i���*i�����m��5GL0�&<']_2�F�	P�k�M�Tn���(w�+�&�$Y%	����;'q9@|PܦR8�q&$g�;�=iA��^[3�J�!H`2�i��%�J��O���0n����[�p�z:X�\���#��� p��'ff�y�-x���+��0��aY-yl�����`�^��v�fy�*.D��a8��~�V��o�By�
���r�:ѩ]i
C+HU��/�t��4�AHo��K��b����E�j;e�7r�w�n���,|���Q$��]�c�+��j�n9���Dgd��C��T�]����\�TN��Y�WG��� 0�4�&��LӅ��v��:�%�\�Ǝv,�dC4*��f�nX�9BM�e��9?����w��Ce)y9JCz�r�;���+*J��ml��	�(q������0y^,���ԫ1j	��M#�=��l��LM��G)�0� �q��ܞ8:O弯I4;�h_9�����L_Tm�Ը��������+i��%����U���[���8���t��߲�� -���(������-W�=����P>b�x �yo\��wr.����ϓJ�lE4ZBslbM������r��$�Ο�"�&M��,&�0���wby�G���)IF(V ��Oa��q+ʔH�~m�bi���×uV�M9<sf���Jk����P~�8ZܘY�̼\oN��	W������|�m�6B��]��
����$h��4GѦ`;C���g?���mxa�-}FXD��N0u��?n�\o���B**����z0������������e>�u?��y7���\1�Uj�KP��8��!�@��.Q!\�=��B���V!ss�!�_�T10g��0Hs���{��+�a{�Z���"�O�����e��=�s'�(�U�m�u`ͥ�R.�R`SAsN�.����EDB5� �W� +,a�H�ޤ^c~�����t=�e;k�٘`�)��k���Þ��bd�ڶ*g��>�@̨��Z�uX  v��2j�
s]��!G�u�����^1f�\llEMnvw�b�=6�lb`{�
)�(��\�������`2�b�f"|y<��]�h���q�{x��P�̅yV�1d!��[��U��x@��k�kB�f���6IE��D��Pq�t�ځ�ǳTB��P	�R�	�y�v,T%��U3�
QU< G/]<��j��`а��܎��-��
v9*���#{�n�-�޵	:��-�%�*�L�s�L�Jc*���[�K
�4񚟥�t�[`X'�R$�A9����x� X�D�r��Ѿ%7�π�P����I~ɇ<��\� ����~1�~9����X@�i�_e�q��yK*�����UpV��1�M�睲�,f:���}��hҗ���H)	���"<I{��S��C�.n�Ȓ`a�o�@��R4��U1B�q���9Dlq�.�̕=v�%����Q$��:G�r����w��k�{TQ	+6�`n�C�^�/�g�qv���'���[�n�
o�DP�*�Ű(���ܶ\kU��T�@׆-g��6g��"�5wZ70Ce�g5�F���1W_�F9�����V)u;��nVf6D��h�y�B*�hI͙DMω
0]jŤaAD)���5�euR��J�v��Q���
�#�>1f�]�ښP��F~�o����a�A����Z��b�,<�$��p>+�$e/	A��b&n\Ұ�9�X�\v��AFu�����} (�v�-
�x���X�
oE"@L��g�6�e�SQ�i@�E׌v�f�:	!�ZMRr�<z�.�T�P�eI͜��!��Tr�cҥ�g��A
v��LR�1�^�[����,uLD@.[,`]�E�]�������{��Nu���	ǈ&f��l|O1��J��!�e���=!VD}�3h�;�sw뎢�:K騻]N�pcc͞���S<w1ɨ�eU��%�N���'����k:�W��ώ��G��t�C*'��#���\����2�E��-f�1���WA�aZ��*G�{�����?5c>�F?|]s~�k=���}���ү�w���U�?���2�x��o��_��;m�7��������Pz��= ��w/��~��C�;,�����G�w�.࢘�z�a�=��J�5{�y������*�?,��oy��Ϊ��~�����kRR�~ ��n��7ȏP����pW�~����~����㥃��ñ�X��m�cGۧ.�7(�}
/�|�l
oY��\4z��zP>����wb_e8�7�W?8���4S":�~��ч�蚟#�J�E�rzF�|�T�-rr9òMAt��(_%XL%�HŢ�^�+5E.���F�)��Eg(^�ŕ���Ĕ$���L;������Z��<^ C���=�5��.���B��(��=��C� ^#.�s����5�bø��[z���A��g�3���N
�QUD{B:Z[one�C�ѕ���xN�eSQ˅?�;"��<�o�+����YB@�]��1$��pl�M4f>e�O�ꥀl����V8q��Y��M���+xjӘ�%:�I&��X�̂��D����d�D(�6����ү0+̮z|J%$
��צv�~�q�`�:��@�,qh"cI4=� n�^�dx��U�sIiȪ�c
[�:/HƟ�Լ0����+��q�\\r$a�?ҩ�[�/(EI�ZB9D�h�H�[��ѱ�1���k�Mh��; N'~�����ˀ{��䚻g� �M\��g!��#��e�Fq��]xqŘ��ݰ��ҜxE;�dwJR*�%��9��V
5�a>1F`ֲ)�D��ma��ZK �e=x�_��󞩞�'��Aqv	��/:Z$�vlJ��Eȕ��Y5���'aٿ�<J�,�	Sf��Vb�h�g�xpK��u�վB([G�i��oQ�T�۫��7]:z;t?c���7��c^�0�-q��SXa����@�7�70��7�p�p����*�?�_�7v2,�'89
H�e5E!F��=Z�XQ��By4X������%)I[�J�� 
����w���wo���W���U�����f�׎���������i��>������yߵ��^�/�~���� �ʼr������O�kka��1������	�������D�So��6�o����e��>�����o�����7�_~��
���s���0WR���w�!��?%e����h^8m��?q�������9��)[gyJ���/β9��7�S�)|ؽ��~�{����'/(�F����FrJ/���)����Qq����D]Y�[�vSVmm{��ǉ��4a�~���靗W��N�'`��⥫����܁��=���$*���M�Q�??���Sf�S_x|�9?��������~��??N[�?�)p~)  
2022-12-12 13:15:06 V/Net 2864518580: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)
com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (String)"\u001F�\u0008\u0000\u0000\u0000\u0000\u0000\u0000\u0003�zgo�X����\u0015����\u001B\u001A��$�=�\u00190S\u0014�D1�o\u001F\u000C�3\u0017��\u001F�\u000E�ig�\u0003�?X>u*��㣪��_�B]o*���"���\u000F��M���CP>���\u001D\u00168��l6�͇>���wa����)�"(�w��}�}�\u007F�)����}_?\u0005͐��\u000FTU�A�?]�:x�x\u001FW�\u000F}0�����6^�]�?�W�\u0009{�O|�'�x���v��Ϳfud�\u0019?
��,�"x~h+�껯P�*)�`����*ϫ�'4c\u0012Lu��_QM����~0&^����5)�>q��s��\u0019��'O�l\u0013�A������ɋ�]�/y����󠌂��u\u000F�6ȟ\u001F>��A�\u007F���/\u001Fv\u001F=����e��N���~J��B�d�\u000C/��|�Z����a�Vy�\u0011��P?��i�\u0015%\u0006?c�U\u0019<ݝ��z��\u0018�
�\u00157)���w%�2z
�1��aӵ������]�U\u000F�о�TeжU����I���\u001C���WH�A�˕\u001F�k��\u001A\u0003*Nr��}��w�x�ӿ��t�w^U�i�.\u0006��\u000E��0��I��/���\u000Ee���w��8𲤌6I���`�%}p\u000F�2���*7I��\u0002oh"[truncated 5724 chars]; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:727)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2538)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:698)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4817)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)
	at com.rxf113.miraiqqbot.chat.HttpUtil.sessionReq(HttpUtil.java:48)
	at com.rxf113.miraiqqbot.chat.MiraiConfig.getAnswerByChatGPT(MiraiConfig.java:120)
	at com.rxf113.miraiqqbot.chat.MiraiConfig.lambda$afterSingletonsInstantiated$0(MiraiConfig.java:98)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:626)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:626)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by rxf113** [comment]
是的，现在请求都403，好像是升级了安全策略。

**Comment by dzy32** [comment]
> 是的，现在请求都403，好像是升级了安全策略。

这个预计会修复吗

**Comment by rxf113** [comment]
> 

周末尝试一下

**Comment by rxf113** [comment]
> > 是的，现在请求都403，好像是升级了安全策略。
> 
> 这个预计会修复吗

周末尝试一下
